#!/bin/bash

dark_gray="0xff414550"
light_gray="0xffe2e2e3"
orange="0xffd65d0e'"

# Colors taken from tokyonight theme
red="0xfff7768e"
blue="0xff7aa2f7"
transparent="0x00000000"

options=(
    style=round
    width=6.0
    hidpi=on
    active_color="$orange"
    inactive_color="$dark_gray"
)

borders "${options[@]}"
